### ISSUE TITLE
android - meta tags are required

### ISSUE THREAD

**Issue by RasmusKOlsen** [Stuart-campbell/RushCore#1]
Hi.

I found what seems to be either a documentation or an implementation error. 

The meta tags seems to be required in the android manifest, or a null pointer is thrown:
 
        <meta-data android:name="Rush_db_version" android:value="1" />

```
    <!-- Database name -->
    <meta-data android:name="Rush_db_name" android:value="poly.danalock.db" />

    <!-- Setting this to true will cause a migration to happen every launch,
    this is very handy during development although could cause data loss -->
    <meta-data android:name="Rush_debug" android:value="false" />

    <!-- Setting this to true mean that tables will only be created of classes that
    extend RushObject and are annotated with @RushTableAnnotation -->
    <meta-data android:name="Rush_requires_table_annotation" android:value="false" />
```

The error seems to happen in AndroidRushConfig.java line 32 - it is expected that meta tags are defined within the application.

For clarity it might also be worth changing the documentation regarding these meta tags to make it clear that they should be childs of theapplication tag.

**Comment by Stuart-campbell** [comment]
Hi

Could you reopen this issue on RushOrm instead as its Android specific so not an issue with RushCore.

https://github.com/Stuart-campbell/RushOrm

This is the first time I have used git submodules great in theory, but does mean its easy to end up in a different repo.

Thanks
